#!/bin/bash
# 机械臂失能问题 - 完整修复与测试指南

echo "======================================================================="
echo "                 机械臂失能摔落问题 - 修复总结"
echo "======================================================================="
echo ""
echo "问题现象:"
echo "  运行 python3 button_action_ros2.py 时，MoveIt2规划失败后"
echo "  机械臂突然失能并摔落"
echo ""
echo "根本原因:"
echo "  1. MoveIt2规划组名称不匹配 ('piper_arm' vs 'arm')"
echo "  2. SDK切换时未强制重新使能机械臂"
echo ""
echo "======================================================================="
echo "                           修复内容"
echo "======================================================================="
echo ""
echo "✅ 修复1: 规划组名称 (button_action_ros2.py:651)"
echo "   修改前: goal_msg.request.group_name = \"piper_arm\""
echo "   修改后: goal_msg.request.group_name = \"arm\""
echo ""
echo "✅ 修复2: SDK使能保护 (button_action_ros2.py:620)"
echo "   添加: piper.EnableArm(7) + time.sleep(0.05)"
echo "   作用: 防止规划失败时机械臂失能"
echo ""
echo "✅ 同步修复: button_actions.py (同样的修改)"
echo ""
echo "======================================================================="
echo "                           测试步骤"
echo "======================================================================="
echo ""
echo "步骤1: 验证修复内容"
echo "----------------------------------------------------------------------"
./test_moveit_fix.sh
echo ""
echo "步骤2: 启动MoveIt2 (新终端)"
echo "----------------------------------------------------------------------"
echo "  cd /home/robot/button/V4.0/project2"
echo "  ./start_moveit2_clean.sh"
echo ""
echo "步骤3: 测试规划组名称 (可选)"
echo "----------------------------------------------------------------------"
echo "  cd /home/robot/button/V4.0/project2"
echo "  python3 test_moveit_planning_group.py"
echo ""
echo "步骤4: 运行完整测试"
echo "----------------------------------------------------------------------"
echo "  cd /home/robot/button/V4.0/project2"
echo "  python3 button_action_ros2.py"
echo ""
echo "预期结果:"
echo "  ✓ MoveIt2规划成功 (不再报错 'Cannot find planning configuration')"
echo "  ✓ 即使规划失败，机械臂保持使能，不会摔落"
echo ""
echo "======================================================================="
echo "                        额外安全建议"
echo "======================================================================="
echo ""
echo "1. 如果仍然失能，尝试修改 EnableArm 参数:"
echo "   piper.EnableArm(0x7F)  # 或 127，使能全部7个轴"
echo ""
echo "2. 在关键操作前添加使能检查:"
echo "   def ensure_arm_enabled():"
echo "       arm_status = piper.GetArmStatus()"
echo "       if arm_status.arm_status != 0:"
echo "           piper.EnableArm(7)"
echo "           time.sleep(0.1)"
echo ""
echo "3. 增加规划失败重试机制 (已在代码中实现)"
echo ""
echo "======================================================================="
echo "                         故障排查"
echo "======================================================================="
echo ""
echo "如果问题仍然存在:"
echo ""
echo "A. 检查MoveIt2状态"
echo "   pgrep -f move_group  # 应该有进程ID"
echo "   ros2 topic list | grep joint_states  # 应该有输出"
echo ""
echo "B. 检查SRDF配置"
echo "   grep 'group name=' ~/piper_ros2/src/piper_description/config/piper.srdf"
echo "   # 应该看到: <group name=\"arm\">"
echo ""
echo "C. 检查SDK连接"
echo "   在Python中运行:"
echo "   from piper_sdk import C_PiperInterface"
echo "   piper = C_PiperInterface()"
echo "   piper.ConnectPort()  # 应该返回True"
echo "   piper.EnableArm(7)   # 应该无报错"
echo ""
echo "D. 查看详细日志"
echo "   在 button_action_ros2.py 中设置:"
echo "   DEBUG = True  # 启用详细日志"
echo ""
echo "======================================================================="
echo "                     技术参考资料"
echo "======================================================================="
echo ""
echo "- 修复文档: MOVEIT2_ARM_DISABLE_FIX.md"
echo "- MoveIt2错误码: https://moveit.picknik.ai/foxy/api/html/"
echo "- Piper SDK参数: EnableArm(7) = 使能6关节+夹爪"
echo ""
echo "======================================================================="
echo "修复完成 - 2025-11-23"
echo "======================================================================="
